[package]
name = "omni_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
file_ref={ git="https://github.com/SuccessfullyFailed/file_ref.git" }
regex = "1.11.1"

[build-dependencies]
crate_manager={ git="https://github.com/SuccessfullyFailed/crate_manager.git" }