name: Update No-Build-Script Branch

on:
  push:
    branches:
      - main

jobs:
  update_no_build_script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up git configuration
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Create or switch to the no-build-script branch
      - name: Create/Switch to no-build-script branch
        run: |
          git fetch origin no-build-script || true
          git checkout no-build-script || git checkout -b no-build-script

      # Sync changes from main branch
      - name: Merge changes from main
        run: |
          git merge origin/main --no-edit

      # Remove or modify build.rs
      - name: Remove build.rs
        run: |
          rm -f build.rs
          git add -u
          sed -i '/^\[build-dependencies\]/,/^$/d' Cargo.toml
          git add Cargo.toml
          git commit -m "Remove build.rs for no-build-script branch" || echo "No changes to commit"

      # Push changes to the no-build-script branch
      - name: Push changes
        run: |
          git push origin no-build-script
